### ISSUE TITLE
Heretic's Heaven

### ISSUE THREAD

**Issue by EmanuelG-Gaming** [guiYMOUR/mindustry-creator-mod#2]
Well, this mod should be yeeted out of the entirety of Github and Mindustry.

Most of the sprites are either stolen or completely out of the place (heresy). Some of the mod's sprites are downloaded from Google Images, without giving them a credit. To add extra info on the stealing, you've gathered sprites from other repositories, again, without credit. Please make original sprites. Thank you.

**Comment by AzhurniyBaklan** [comment]
> Well, this mod should be yeeted out of the entirety of Github and Mindustry.
> 
> Most of the sprites are either stolen or completely out of the place (heresy). Some of the mod's sprites are downloaded from Google Images, without giving them a credit. To add extra info on the stealing, you've gathered sprites from other repositories, again, without credit. Please make original sprites. Thank you.

this issue was so obnoxious that this mod got blacklisted.

**Comment by AzhurniyBaklan** [comment]
> Well, this mod should be yeeted out of the entirety of Github and Mindustry.
> 
> Most of the sprites are either stolen or completely out of the place (heresy). Some of the mod's sprites are downloaded from Google Images, without giving them a credit. To add extra info on the stealing, you've gathered sprites from other repositories, again, without credit. Please make original sprites. Thank you.

To close this question once and for all, we with #modding-general decided to blacklist it altogether. We are tired of this mod. It was bad since forever and never changed.

**Comment by EmanuelG-Gaming** [comment]
> > Well, this mod should be yeeted out of the entirety of Github and Mindustry.
> > Most of the sprites are either stolen or completely out of the place (heresy). Some of the mod's sprites are downloaded from Google Images, without giving them a credit. To add extra info on the stealing, you've gathered sprites from other repositories, again, without credit. Please make original sprites. Thank you.
> 
> To close this question once and for all, we with #modding-general decided to blacklist it altogether. We are tired of this mod. It was bad since forever and never changed.

yes
